added contributing.md
hyphacoop/remote pull request #9
Opened 2020-03-21 20:51 UTC by ASoTNetworks

2020-03-21 22:34 UTC, benhylau commented
We already have https://github.com/hyphacoop/remote/blob/master/CONTRIBUTING.md and this is a different file. What are the things you changed, and why not edit existing file?

2020-03-23 17:45 UTC, ASoTNetworks commented
I was following the link to /contributing which it 404s so thinking I should create a new file and didn't notice CONTRIBUTING.md

I changed the references to what applies to Hypha in that file.

2020-03-23 17:51 UTC, benhylau commented on contributing.md
> +        $ git clone git@github.com:<your-username>/<repository-name>.git
```suggestion
        $ git clone git@github.com:<your-username>/remote.git
```

2020-03-23 17:52 UTC, benhylau commented on contributing.md
> +        $ git clone git@github.com:hyphacoop/<repository-name>.git
```suggestion
        $ git clone git@github.com:hyphacoop/remote.git
```

2020-03-23 17:55 UTC, benhylau commented on contributing.md
> +    - Allow up to 3 days for review. If you don’t get any feedback by then, you can merge it without review.
```suggestion
    If you have commit rights on the repo, you should merge your own PR, but have someone else review it first. Allow up to 3 days for review. If you don’t get any feedback by then, you can merge it without review.
```

2020-03-23 17:57 UTC, benhylau commented on contributing.md
> +title-display: EN
```suggestion
```

2020-03-23 17:58 UTC, benhylau commented on contributing.md
> +
```suggestion

_Contributing Guidelines adopted from [Environmental Data and Governance Initiative (EDGI)](https://envirodatagov.org/)._

```

2020-03-23 17:58 UTC, benhylau commented on contributing.md
> +### Submitting Feedback, Requests, and Bugs
```suggestion
### Submitting Feedback, Requests, and Bugs

```

2020-03-23 17:59 UTC, benhylau commented on contributing.md
> +        https://github.com/hyphacoop/<repository-name>/issues
```suggestion
        https://github.com/hyphacoop/remote/issues
```

2020-03-23 18:02 UTC, benhylau commented on contributing.md
> +Our process for submitting feedback, feature requests, and reporting bugs usually begins by opening [GitHub issues](https://help.github.com/articles/about-issues/). Each project repository generally
```suggestion
This resource accepts feedback, feature requests, and bug reports by opening [GitHub issues](https://github.com/hyphacoop/remote/issues).
```

2020-03-23 18:02 UTC, benhylau commented on contributing.md
> +
```suggestion
```

2020-03-23 18:02 UTC, benhylau requested changes
Please see comments.

2020-03-23 18:33 UTC, benhylau approved these changes

2020-03-23 18:39 UTC, merged